wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
train_steps:
  desc: null
  value: 10000
eps_safe:
  desc: null
  value: 0.05
eps_unsafe:
  desc: null
  value: 0.2
eps_grad:
  desc: null
  value: 0.05
w_safe:
  desc: null
  value: 1
w_unsafe:
  desc: null
  value: 40
w_grad:
  desc: null
  value: 1
dt:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740280235.039072
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.21
      5: 0.14.2
      8:
      - 4
      - 5
