wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744834176.527755
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.9.21
      5: 0.14.2
      8:
      - 4
      - 5
dataset_path:
  desc: null
  value: safe_rl_dataset_images_ALLUNSAFE_big_obstacle_3000traj.npz
validation_split:
  desc: null
  value: 0.1
input_channels:
  desc: null
  value: 3
latent_dim:
  desc: null
  value: 4
action_dim:
  desc: null
  value: 2
hidden_dim:
  desc: null
  value: 400
cbf_hidden_dim:
  desc: null
  value: 128
cbf_layers:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 15
safe_distance:
  desc: null
  value: 7.0
eps_safe:
  desc: null
  value: 0.08
eps_unsafe:
  desc: null
  value: 0.15
gradient_loss_weight:
  desc: null
  value: 2.0
eps_grad:
  desc: null
  value: 0.02
checkpoint_interval:
  desc: null
  value: 1
use_cql_actions:
  desc: null
  value: true
cql_actions_weight:
  desc: null
  value: 1.0
num_action_samples:
  desc: null
  value: 10
temp:
  desc: null
  value: 0.7
detach:
  desc: null
  value: true
seed:
  desc: null
  value: 1
