wandb_version: 1

environment:
  desc: null
  value: DubinsCarEnv
goal_position:
  desc: null
  value:
  - 20
  - 21
max_velocity:
  desc: null
  value: 3.0
dt:
  desc: null
  value: 0.1
safe_distance:
  desc: null
  value: 4.0
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741044606.28025
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.21
      5: 0.14.2
      8:
      - 4
      - 5
device:
  desc: null
  value: mps
