wandb_version: 1

project:
  desc: null
  value: OSRL-baselines
group:
  desc: null
  value: null
name:
  desc: null
  value: null
prefix:
  desc: null
  value: BCQL
suffix:
  desc: null
  value: ''
logdir:
  desc: null
  value: logs
verbose:
  desc: null
  value: true
outliers_percent:
  desc: null
  value: null
noise_scale:
  desc: null
  value: null
inpaint_ranges:
  desc: null
  value: null
epsilon:
  desc: null
  value: null
density:
  desc: null
  value: 1.0
task:
  desc: null
  value: OfflineCarCircle-v0
dataset:
  desc: null
  value: null
seed:
  desc: null
  value: 0
device:
  desc: null
  value: cpu
threads:
  desc: null
  value: 4
reward_scale:
  desc: null
  value: 0.1
cost_scale:
  desc: null
  value: 1
actor_lr:
  desc: null
  value: 0.001
critic_lr:
  desc: null
  value: 0.001
vae_lr:
  desc: null
  value: 0.001
phi:
  desc: null
  value: 0.05
lmbda:
  desc: null
  value: 0.75
beta:
  desc: null
  value: 0.5
cost_limit:
  desc: null
  value: 10
episode_len:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 512
update_steps:
  desc: null
  value: 100000
num_workers:
  desc: null
  value: 8
a_hidden_sizes:
  desc: null
  value:
  - 256
  - 256
c_hidden_sizes:
  desc: null
  value:
  - 256
  - 256
vae_hidden_sizes:
  desc: null
  value: 400
sample_action_num:
  desc: null
  value: 10
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
num_q:
  desc: null
  value: 2
num_qc:
  desc: null
  value: 2
PID:
  desc: null
  value:
  - 0.1
  - 0.003
  - 0.001
eval_episodes:
  desc: null
  value: 10
eval_every:
  desc: null
  value: 2500
_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739230446.488048
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.9.21
      5: 0.14.2
      8:
      - 4
      - 5
