_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-arm64
cql_actions_weight:
    value: 0
detach:
    value: true
device:
    value: mps
dim_hidden:
    value: 128
dt:
    value: 0.1
environment:
    value: DubinsCarEnv
goal_position:
    value:
        - 20
        - 21
max_velocity:
    value: 3
num_action_samples:
    value: 10
num_hidden_dim:
    value: 3
safe_distance:
    value: 5
seed:
    value: 42
step_count:
    value: 25000
temp:
    value: 1
use_cql_actions:
    value: false
